name: Build Steps
description: "Build Steps"
inputs:
  name:
    description: "Name of the action"
    required: true
runs:
  using: composite
  steps:
    - name: ${{ input.name }}-base
      uses: docker/build-push-action@v3
      with:
        context: "{{ defaultContext }}:${{ inputs.name }}"
        push: true
        cache-to: type=inline
        tags: sacnussem/devcontainer:${{ inputs.name }}
    - name: ${{ input.name }}-base
      uses: docker/build-push-action@v3
      with:
        context: "{{ defaultContext }}:${{ inputs.name }}"
        file: quartus.Dockerfile
        push: true
        cache-from: type=inline, ref=sacnussem/devcontainer:${{ inputs.name }}
        tags: sacnussem/devcontainer:${{ inputs.name }}-quartus
