name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names: 
         - hpc-focal
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30720
          swap-size-mb: 1024
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ${{ matrix.names }}
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.names }}"
          push: true
          tags: sacnussem/devcontainer:${{ matrix.names }}
