name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names:
          - hpc-focal
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30720
          swap-size-mb: 1024
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/checkout
          
      # it doesn't support dynamic 'uses'
      - uses: ./hpc-focal
        if: ${{ matrix.names == 'hpc-focal' }}
